services:
  - type: web
    name: dulichviet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.tourapp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SETTINGS_MODULE
        value: backend.tourapp.settings 